title: Minimal theme
logo: /assets/img/logo.png
description: Emulation Platform for Software-Defined Wireless Networks
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

site_index: /index.md
site_get_started: /get-started


# Reading Files
include:
  - .htaccess
  - _pages
  - files