title: Minimal theme
logo: /assets/img/logo.png
description: Emulation Platform for Software-Defined Wireless Networks
show_downloads: true
google_analytics:
remote_theme: mmistakes/minimal-mistakes



# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache