title: Mininet-WiFi
logo: /assets/img/logo.png
bookpt: /assets/img/book-pt.png
description: Emulation Platform for Software-Defined Wireless Networks
show_downloads: true
google_analytics: true
baseurl: "/"
theme: jekyll-theme-minimal
markdown: kramdown
heading_anchors: true

site_index: /index.md
site_get_started: /get-started
site_usage: /usage
site_advanced: /advanced
site_commands: /commands
site_80211p: /80211p
site_containernet: /containernet
site_sumo: /sumo
site_p4: /p4
site_manet: /manet
site_propagation: /propagation
site_mobility: /mobility
site_faq: /faq
site_cases: https://docs.google.com/spreadsheets/d/1laEhejMg6th-Urgc-_RqBi2H6m308Rnh9uJpKZavEio
site_book: /book
site_publications: https://github.com/intrig-unicamp/mininet-wifi/wiki/Publications,-Citations-&-Users
site_demos: https://www.youtube.com/playlist?list=PLccoFREVAt_4nEtrkl59mjjf5ZzRX8DZA
site_sixlowpan: /sixlowpan
site_mac80211_hwsim: /mac80211_hwsim


# Reading Files
include:
  - .htaccess
  - _pages
  - files
