title: Minimal theme
logo: /assets/img/logo.png
description: Emulation Platform for Software-Defined Wireless Networks
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

site_index: /index.md
site_get_started: /get-started
site_part1: /part1
site_part2: /part2
site_part3: /part3
site_part4: /part4
site_80211p: /80211p
site_propagation: /propagation
site_mobility: /mobility
site_faq: /faq
site_test: /test


# Reading Files
include:
  - .htaccess
  - _pages
  - files